CREATE TABLE customer
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 NO MAXVALUE CACHE 1 ),
    customer_address character varying(255) NOT NULL,
    customer_location character varying(255)  NOT NULL,
    customer_name character varying(255) ,
    customer_pan_number character varying(9) NOT NULL,
    CONSTRAINT customer_pkey PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 NO MAXVALUE CACHE 1 ),
    order_name character varying(255) ,
    customer_id bigint NOT NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (id),
    CONSTRAINT fk_customer FOREIGN KEY (customer_id)
        REFERENCES customer (id) 
);

CREATE TABLE order_details
(
    order_detail_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 NO MAXVALUE CACHE 1 ),
    order_qty integer,
    purchase_amt double precision,
    order_id bigint NOT NULL,
    CONSTRAINT order_details_pkey PRIMARY KEY (order_detail_id),
    CONSTRAINT uk_orderId UNIQUE (order_id),
    CONSTRAINT fk_orderId FOREIGN KEY (order_id)
        REFERENCES public.orders (id) ,
    CONSTRAINT order_details_order_qty_check CHECK (order_qty >= 2)
);

INSERT INTO customer(id, customer_address, customer_location, customer_name, customer_pan_number) VALUES (?, ?, ?, ?, ?);

INSERT INTO order_details(order_detail_id, order_qty, purchase_amt, order_id) VALUES (?, ?, ?, ?);

INSERT INTO orders(id, order_name, customer_id) VALUES (?, ?, ?);
